# -*- coding: utf-8 -*-
"""WC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P-IhazAfdyYsQHrGVNmYq5TyuWbaxakW
"""

import glob
import cv2
import array
import matplotlib.pyplot as plt
import numpy
import os
from scipy.io import loadmat
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.constraints import maxnorm
from keras.optimizers import SGD
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import load_img
from keras.applications import imagenet_utils
from keras import regularizers
from sklearn.datasets import make_regression
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from numpy import argmax
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
#from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
f = open("/content/drive/My Drive/Keras/EvalSet_train", "r")
content_train = f.read()
f.close()
f = open("/content/drive/My Drive/Keras/EvalSet_test", "r")
content_test = f.read()
f.close()
# print(content_test)
content_train = content_train.split("\n")
content_test = content_test.split("\n")


model1 = Sequential()
model1.add(Conv2D(32, kernel_size=(3,3), padding='same', activation='relu'))
model1.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
# model1.add(Dense(3, activation='softmax'))
model1.add(Conv2D(64, kernel_size=(3,3), padding='same', activation='relu'))
model1.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
# model1.add(Dense(3, activation='softmax'))
model1.add(Conv2D(128, kernel_size=(3,3), padding='same', activation='relu'))
model1.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
# model1.add(Dense(3, activation='softmax'))
model1.add(Conv2D(256, kernel_size=(3,3), padding='same', activation='relu'))
model1.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
model1.add(Flatten())
# model1.add(Dense(512, activation='relu', kernel_constraint=maxnorm(3),))
model1.add(Dense(3, kernel_initializer='normal', activation='sigmoid'))
# model1.add(Dense(1, kernel_initializer='normal'))
# model1.add(Dense(3, activation='softmax'))
epochs = 3
lrate = 0.0005
decay = lrate/epochs
sgd = SGD(lr=lrate)
model1.compile(loss='mean_squared_error',optimizer=sgd, metrics=['accuracy'])
# model1.summary()




# model2 = Sequential()
# model2.add(Conv2D(32,input_shape =(64, 64, 3), kernel_size=(3,3), padding='same', activation='relu'))
# model2.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
# # model2.add(Dense(3, activation='softmax'))
# model2.add(Conv2D(64, kernel_size=(3,3), padding='same', activation='relu'))
# model2.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
# # model2.add(Dense(3, activation='softmax'))
# model2.add(Conv2D(128, kernel_size=(3,3), padding='same', activation='relu'))
# model2.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
# model2.add(Dense(3, activation='softmax'))


# print(trsets[0])
k = 0
imgpath = os.getcwd()
imgpath = os.path.join(imgpath, "/content/drive/My Drive/Keras/our_data")
# for i in range(254):
# for j in range(1,4):
# # im = Image.open("data/"+str(i)+"/"+str(j)+".jpg")
# # newsize = (64, 64) 
# # im = im.resize(newsize)
# imgpath1 = os.path.join(imgpath, str(i))
# imgpath1 = os.path.join(imgpath1, str(j) + ".jpg")
# im = load_img(imgpath1, target_size = (64, 64))
# pixel[i][j] = img_to_array(im)
# toimage(pixel[21][3]).show()
y = loadmat('/content/drive/My Drive/Keras/ImageMaster.mat')
# y1 = y['imagemaster'][0][i].tolist()[0][0][2].tolist()[0]
# print(len(trsets[0]))
for i in range(4):
    trsets = []
    tesets = []
    r = []
    # print(trsets[i][0])
    # t = [None in range(len(content_train[i].split(',')))]
    t = content_train[i].split(',')
    # print("     "+str(len(t)))
    for j in t:
        if j != '':
            r.append(int(j))
    # print(r)
    trsets = r
    t = content_test[i].split(',')
    for j in t:
        if j != '':
            r.append(int(j))
    # print(r)
    tesets = r
    train_x = []
    train_x1 = [i for  i in range(254)]
    train_y = []
    train_y1 = []
    train_y2 = []
    test_x = []
    test_y = []
    test_y1 = []
    test_y2 = []
    # print(len(trsets[i]))
    for j in trsets:
        # print(y['imagemaster'][0][j].tolist()[0][0][1].tolist()[0])
        name = y['imagemaster'][0][j].tolist()[0][0][1].tolist()[0]
        # tag1 = y['imagemaster'][0][j].tolist()[0][0][2][0]
        # tag2 = y['imagemaster'][0][j].tolist()[0][0][2][0]
        train_y.append(y['imagemaster'][0][j].tolist()[0][0][2][0])
        # train_y[i].append(y['imagemaster'][0][j].tolist()[0][0][2][0])
        #name = os.path.join(imgpath, name)
        #img1path = os.path.join(name, "1.jpg")
        # img2path = os.path.join(name, "3.jpg")
        name = os.path.join("/content/drive/My Drive/Keras/our_data", name)
        listing = os.listdir(name)
        img1path = os.path.join(name,listing[0])

        im1 = load_img(img1path, target_size=(64, 64))
        # im2 = load_img(img2path, target_size=(64, 64))
        im1 = img_to_array(im1)
        # im2 = img_to_array(im2)
        train_x.append(im1)
        # train_x[i].append(im2)
    for j in tesets:
        # print(y['imagemaster'][0][j].tolist()[0][0][1].tolist()[0])
        name = y['imagemaster'][0][j].tolist()[0][0][1].tolist()[0]
        name = y['imagemaster'][0][j].tolist()[0][0][1].tolist()[0]
        # tag = y['imagemaster'][0][j].tolist()[0][0][2][0]
        test_y.append(y['imagemaster'][0][j].tolist()[0][0][2][0])
        # test_y[i].append(y['imagemaster'][0][j].tolist()[0][0][2][0])
        name = os.path.join("/content/drive/My Drive/Keras/our_data", name)
        listing = os.listdir(name)
        img1path = os.path.join(name,listing[0])
        #img1path = os.path.join(name, "1.jpg")
        # img2path = os.path.join(name, "3.jpg")
        im1 = load_img(img1path, target_size=(64, 64))
        # im2 = load_img(img2path, target_size=(64, 64))
        im1 = img_to_array(im1)
        # im2 = img_to_array(im2)
        test_x.append(im1)
        # test_x[i].append(im2)
    # print(test_x)
    for j in range(len(trsets)):
        if train_y[j] == str("heavy"):
            train_y1.append(0)
            # train_y2.append(0.165)
        elif train_y[j] == str("medium"):
            train_y1.append(1)
            # train_y2.append(0.5)
        elif train_y[j] == str("light"):
            train_y1.append(2)
            # train_y2.append(0.83)
    train_y1 = numpy.array(train_y1)
    # print(train_y1)
    train_y1 = np_utils.to_categorical(train_y1, num_classes=3)
    for j in range(len(tesets)):
        if test_y[j] == str('heavy'):
            test_y1.append(0)
            test_y2.append(0.165)
        elif test_y[j] == str('medium'):
            test_y1.append(1)
            test_y2.append(0.5)
        elif test_y[j] == str('light'):
            test_y1.append(2)
            test_y2.append(0.83)
    test_y1 = numpy.array(test_y1)
    test_y1 = np_utils.to_categorical(test_y1, num_classes=3)
    # print(argmax(np_utils.to_categorical(test_y1[i], 3)))
    # plt.plot(train_x1, train_y1)
    # plt.show()
    # print(train_y1)
    # train_x = numpy.vstack(train_x)

    # print(train_x)
    # print(train_y)
    # images = [cv2.imread(file) for file in glob.glob("C:/Users/manak/Documents/WC-Project/Keras/data/*.jpg")]
    print("SET :"+str(i+1))
    tr_x = numpy.array(train_x)
    tr_y = numpy.array(train_y1)
    tr_y1 = numpy.array(train_y2)
    te_x = numpy.array(test_x)
    te_y = numpy.array(test_y1)
    te_y1 = numpy.array(test_y2)
    # print(tr_x.shape)
    # print(tr_y.shape)
    # print(te_x.shape)
    # print(te_y.shape)
    # regressor = KerasRegressor(build_fn=build_regressor, epochs=100)
    # results=regressor.fit(tr_x,tr_y1)
    # y_pred= regressor.predict(te_x)
    # estimators = []
    # # estimators.append(('standardize', StandardScaler()))
    # estimators.append(('mlp', KerasRegressor(build_fn=baseline_model, epochs=100, batch_size=5, verbose=0)))
    # pipeline = Pipeline(estimators)
    # #estimator = KerasRegressor(build_fn=model1, epochs=100, batch_size=5, verbose=0)
    # kfold = KFold(n_splits=10)
    # results = cross_val_score(pipeline, te_x, te_y, cv=kfold)
    # print("Baseline: %.2f (%.2f) MSE" % (results.mean(), results.std()))
    model1.fit(tr_x,tr_y,validation_data=(te_x, te_y), epochs=epochs)
    # model1.summary()
    scores = model1.evaluate(te_x,te_y, verbose=0)
    feature = model1.predict(te_x)

    print("Accuracy: %.2f%%" % (scores[1]*100))

    result = []#

    for m in feature:
        # print(argmax(m))
        result.append(argmax(m))
    # print(result) 

    results = []

    for j in range(len(tesets)):
        if result[j] == 0:
            # test_y1.append(0)
            results.append(0.165)
        elif result[j] == 1:
            # test_y1.append(1)
            results.append(0.5)
        elif result[j] == 2:
            # test_y1.append(2)
            results.append(0.83)

    fig = plt.figure()
    ax1 = fig.add_subplot(111)

    ax1.scatter(tesets, test_y2, s=10, c='b', marker="s", label='Actual')
    ax1.scatter(tesets,results, s=10, c='r', marker="o", label='Predicted')
    plt.legend(loc='upper left');  
    plt.title("SET: "+str(i+1))
    plt.show()

    train_x.clear()
    train_x1.clear()
    train_y.clear()
    # train_y1.clear()
    test_x.clear()
    test_y.clear()
    # test_y1.clear()
    t.clear()
    trsets.clear()
    tesets.clear()

from google.colab import drive
import glob
import cv2
import array
import matplotlib.pyplot as plt
import numpy
import os
from scipy.io import loadmat
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.constraints import maxnorm
from keras.optimizers import SGD
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import load_img
from keras.applications import imagenet_utils
from keras import regularizers
from sklearn.datasets import make_regression
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from numpy import argmax
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
#from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
f = open("/content/drive/My Drive/Keras/EvalSet_train", "r")
content_train = f.read()
f.close()
f = open("/content/drive/My Drive/Keras/EvalSet_test", "r")
content_test = f.read()
f.close()
# print(content_test)
content_train = content_train.split("\n")
content_test = content_test.split("\n")

drive.mount('/content/drive')

from google.colab import drive
import glob
import cv2
import array
import matplotlib.pyplot as plt
import numpy
import os
from scipy.io import loadmat
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.constraints import maxnorm
from keras.optimizers import SGD
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import load_img
from keras.applications import imagenet_utils
from keras import regularizers
from sklearn.datasets import make_regression
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from numpy import argmax
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
#from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
f = open("/content/drive/My Drive/Keras/EvalSet_train", "r")
content_train = f.read()
f.close()
f = open("/content/drive/My Drive/Keras/EvalSet_test", "r")
content_test = f.read()
f.close()
# print(content_test)
content_train = content_train.split("\n")
content_test = content_test.split("\n")

drive.mount('/content/drive')

model1 = Sequential()
model1.add(Conv2D(32,input_shape =(64, 64, 3), kernel_size=(3,3), padding='same', activation='relu', activity_regularizer=regularizers.l1(0.00001)))
model1.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
# model1.add(Dense(3, activation='softmax'))
model1.add(Conv2D(64, kernel_size=(3,3), padding='same', activation='relu', activity_regularizer=regularizers.l1(0.00001)))
model1.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
# model1.add(Dense(3, activation='softmax'))
model1.add(Conv2D(128, kernel_size=(3,3), padding='same', activation='relu', activity_regularizer=regularizers.l1(0.00001)))
model1.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
# model1.add(Dense(3, activation='softmax'))
model1.add(Conv2D(256, kernel_size=(3,3), padding='same', activation='relu', activity_regularizer=regularizers.l1(0.00001)))
model1.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
model1.add(Flatten())
# model1.add(Dense(512, activation='relu', kernel_constraint=maxnorm(3),))
model1.add(Dense(3, activation='sigmoid', activity_regularizer=regularizers.l1(0.00001)))
# model1.add(Dense(3, activation='softmax'))
epochs = 3
lrate = 0.0005
decay = lrate/epochs
sgd = SGD(lr=lrate)
model1.compile(loss='mean_squared_error',optimizer=sgd, metrics=['accuracy'])
model1.summary() 


k = 0
imgpath = os.getcwd()
imgpath = os.path.join(imgpath, "/content/drive/My Drive/Keras/data")
# for i in range(254):
# for j in range(1,4):
# # im = Image.open("data/"+str(i)+"/"+str(j)+".jpg")
# # newsize = (64, 64) 
# # im = im.resize(newsize)
# imgpath1 = os.path.join(imgpath, str(i))
# imgpath1 = os.path.join(imgpath1, str(j) + ".jpg")
# im = load_img(imgpath1, target_size = (64, 64))
# pixel[i][j] = img_to_array(im)
# toimage(pixel[21][3]).show()
y = loadmat('/content/drive/My Drive/Keras/ImageMaster.mat')
# y1 = y['imagemaster'][0][i].tolist()[0][0][2].tolist()[0]
# print(len(trsets[0]))
for i in range(4):
    trsets = []
    tesets = []
    r = []
    # print(trsets[i][0])
    # t = [None in range(len(content_train[i].split(',')))]
    t = content_train[i].split(',')
    # print("     "+str(len(t)))
    for j in t:
        if j != '':
            r.append(int(j))
    # print(r)
    trsets = r
    t = content_test[i].split(',')
    for j in t:
        if j != '':
            r.append(int(j))
    # print(r)
    tesets = r
    train_x = []
    train_x1 = [i for  i in range(254)]
    train_y = []
    train_y1 = []
    train_y2 = []
    test_x = []
    test_y = []
    test_y1 = []
    test_y2 = []
    # print(len(trsets[i]))
    for j in trsets:
        # print(y['imagemaster'][0][j].tolist()[0][0][1].tolist()[0])
        name = y['imagemaster'][0][j].tolist()[0][0][1].tolist()[0]
        # tag1 = y['imagemaster'][0][j].tolist()[0][0][2][0]
        # tag2 = y['imagemaster'][0][j].tolist()[0][0][2][0]
        train_y.append(y['imagemaster'][0][j].tolist()[0][0][2][0])
        # train_y[i].append(y['imagemaster'][0][j].tolist()[0][0][2][0])
        #name = os.path.join(imgpath, name)
        #img1path = os.path.join(name, "1.jpg")
        # img2path = os.path.join(name, "3.jpg")
        name = os.path.join("/content/drive/My Drive/Keras/data", name)
        listing = os.listdir(name)
        img1path = os.path.join(name,listing[0])

        im1 = load_img(img1path, target_size=(64, 64))
        # im2 = load_img(img2path, target_size=(64, 64))
        im1 = img_to_array(im1)
        # im2 = img_to_array(im2)
        train_x.append(im1)
        # train_x[i].append(im2)
    for j in tesets:
        # print(y['imagemaster'][0][j].tolist()[0][0][1].tolist()[0])
        name = y['imagemaster'][0][j].tolist()[0][0][1].tolist()[0]
        name = y['imagemaster'][0][j].tolist()[0][0][1].tolist()[0]
        # tag = y['imagemaster'][0][j].tolist()[0][0][2][0]
        test_y.append(y['imagemaster'][0][j].tolist()[0][0][2][0])
        # test_y[i].append(y['imagemaster'][0][j].tolist()[0][0][2][0])
        name = os.path.join("/content/drive/My Drive/Keras/data", name)
        listing = os.listdir(name)
        img1path = os.path.join(name,listing[0])
        #img1path = os.path.join(name, "1.jpg")
        # img2path = os.path.join(name, "3.jpg")
        im1 = load_img(img1path, target_size=(64, 64))
        # im2 = load_img(img2path, target_size=(64, 64))
        im1 = img_to_array(im1)
        # im2 = img_to_array(im2)
        test_x.append(im1)
        # test_x[i].append(im2)
    # print(test_x)
    for j in range(len(trsets)):
        if train_y[j] == str("heavy"):
            train_y1.append(0)
            # train_y2.append(0.165)
        elif train_y[j] == str("medium"):
            train_y1.append(1)
            # train_y2.append(0.5)
        elif train_y[j] == str("light"):
            train_y1.append(2)
            # train_y2.append(0.83)
    train_y1 = numpy.array(train_y1)
    # print(train_y1)
    train_y1 = np_utils.to_categorical(train_y1, num_classes=3)
    for j in range(len(tesets)):
        if test_y[j] == str('heavy'):
            test_y1.append(0)
            test_y2.append(0.165)
        elif test_y[j] == str('medium'):
            test_y1.append(1)
            test_y2.append(0.5)
        elif test_y[j] == str('light'):
            test_y1.append(2)
            test_y2.append(0.83)
    test_y1 = numpy.array(test_y1)
    test_y1 = np_utils.to_categorical(test_y1, num_classes=3)
    # print(argmax(np_utils.to_categorical(test_y1[i], 3)))
    # plt.plot(train_x1, train_y1)
    # plt.show()
    # print(train_y1)
    # train_x = numpy.vstack(train_x)

    # print(train_x)
    # print(train_y)
    # images = [cv2.imread(file) for file in glob.glob("C:/Users/manak/Documents/WC-Project/Keras/data/*.jpg")]
    print("SET :"+str(i+1))
    tr_x = numpy.array(train_x)
    tr_y = numpy.array(train_y1)
    tr_y1 = numpy.array(train_y2)
    te_x = numpy.array(test_x)
    te_y = numpy.array(test_y1)
    te_y1 = numpy.array(test_y2)
    # print(tr_x.shape)
    # print(tr_y.shape)
    # print(te_x.shape)
    # print(te_y.shape)
    # regressor = KerasRegressor(build_fn=build_regressor, epochs=100)
    # results=regressor.fit(tr_x,tr_y1)
    # y_pred= regressor.predict(te_x)
    # estimators = []
    # # estimators.append(('standardize', StandardScaler()))
    # estimators.append(('mlp', KerasRegressor(build_fn=baseline_model, epochs=100, batch_size=5, verbose=0)))
    # pipeline = Pipeline(estimators)
    # #estimator = KerasRegressor(build_fn=model1, epochs=100, batch_size=5, verbose=0)
    # kfold = KFold(n_splits=10)
    # results = cross_val_score(pipeline, te_x, te_y, cv=kfold)
    # print("Baseline: %.2f (%.2f) MSE" % (results.mean(), results.std()))
    model1.fit(tr_x,tr_y,validation_data=(te_x, te_y), epochs=epochs)
    # model1.summary()
    scores = model1.evaluate(te_x,te_y, verbose=0)
    feature = model1.predict(te_x)

    print("Accuracy: %.2f%%" % (scores[1]*100))

    result = []#

    for m in feature:
        # print(argmax(m))
        result.append(argmax(m))
    # print(result) 

    results = []

    for j in range(len(tesets)):
        if result[j] == 0:
            # test_y1.append(0)
            results.append(0.165)
        elif result[j] == 1:
            # test_y1.append(1)
            results.append(0.5)
        elif result[j] == 2:
            # test_y1.append(2)
            results.append(0.83)

    fig = plt.figure()
    ax1 = fig.add_subplot(111)

    ax1.scatter(tesets, test_y2, s=10, c='b', marker="s", label='Actual')
    ax1.scatter(tesets,results, s=10, c='g', marker="o", label='Predicted')
    plt.legend(loc='upper left');  
    plt.title("SET: "+str(i+1))
    plt.show()

    train_x.clear()
    train_x1.clear()
    train_y.clear()
    # train_y1.clear()
    test_x.clear()
    test_y.clear()
    # test_y1.clear()
    t.clear()
    trsets.clear()
    tesets.clear()

from google.colab import drive
drive.mount('/content/drive')

